### PR TITLE
Restrictions on other request parameters when 'request' is used

### PR DESCRIPTION
**Pull request by TakahikoKawasaki**

### CODE REVIEW

**Comment by panva** [comment]
Should we rather make that a non-exhaustive list? Leave a room out there for future extensions with new client authentication methods and potentially other attributes.

**Comment by TakahikoKawasaki** [comment]
The list included in this PR does not intend to be exhaustive. Rather, the current sentence excludes other parameters than the `client_id` request parameter. The intention of this PR is to allow other parameters such as `client_secret` and `client_assertion`.

**Comment by panva** [comment]
The point of that sentence was to cover the fact the **only** `client_id` is both an authorization request parameter as well as client authentication one. The ones newly listed are not authorization request parameters.

I get your point but hopefully AS implementers will know not to store these parameters in whatever persisted object.

**Comment by TakahikoKawasaki** [comment]
Listing `client_secret`, `client_assertion` and `client_assertion_type` does not necessarily urge AS implementers to store them somewhere because they are present _outside_ the request object.

The intention is the same as the requirement described in "[7.1.1. Signed Authentication Request](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html#signed_auth_request)" in [CIBA Core 1.0](https://openid.net/specs/openid-client-initiated-backchannel-authentication-core-1_0.html).

> The signed authentication request JWT is passed as an `application/x-www-form-urlencoded` HTTP request parameter with the name `request`. Authentication request parameters MUST NOT be present outside of the JWT, in particular they MUST NOT appear as HTTP request parameters. **Additional HTTP request parameters as required by the given client authentication method, however, MUST be included as `application/x-www-form-urlencoded` parameters (e.g. Mutual TLS client authentication uses `client_id` while JWT assertion based client authentication uses `client_assertion` and `client_assertion_type`).**

The current sentence says as follows.

> Clients MUST NOT combine other _**authorization request parameters**_ with the `request` parameter at the pushed authorization request endpoint other than the `client_id` parameter which may be a part of the client authentication mechanism.

It sounds that you expect AS implementers will think in this way: _"Clients MUST NOT combine other **authorization** request parameters"_ does not exclude `client_secret`, `client_assertion` and `client_assertion_type` because they are **client authentication** parameters and not **authorization** parameters. However, the expression is too subtle to expect AS implementers will reach the same interpretation without deep discussion. In fact, in the past, engineers needed discussion about "client authentication at the backchannel authentication endpoint (CIBA)" to reach the consensus and clarification, CIBA Core [PR 51](https://bitbucket.org/openid/mobile/pull-requests/51/ciba-attempt-to-further-clarify-that-an/diff) ("CIBA: attempt to further clarify that an authentication request can have other HTTP request parameters as required by the client authentication method").

I made this PR on behalf of certain engineers in the industry who had pointed out the ambiguity of the current sentence.

**Comment by jricher** [comment]
Is the requirement really that `request` is sent on its own, always? That seems to be an unnecessary restriction to begin with.

**Comment by panva** [comment]
It is in line with JAR usage and as such promotes re-use of existing authorization request processing pipelines

**Comment by b---c** [comment]
I took a pass at rewording some of the section in question with pull request #35 that hopefully makes things clear.

**Comment by b---c** [comment]
got a couple of approvals on pull request #35 and no objections so I went ahead and merged it

**Pull request closed without merging**
